### PR TITLE
Fix xoom-build-plugin version

### PR DESCRIPTION
**Pull request by hurelhuyag**
I can't find version 1.5.1-SNAPSHOT. That is making the project broken.

### CODE REVIEW

**Comment by VaughnVernon** [comment]
@hurelhuyag Yes, because there is no `xoom-build-plugin` for 1.5.1, only a `vlingo-build-plugin` at that version.

I don't know why those dependencies aren't automatically updated by the release process. /cc @jakzal

**Review by VaughnVernon — APPROVED** [review]

**Comment by VaughnVernon** [comment]
Unfortunately we've got version numbers sprayed all over the XOOM Designer and Turbo source. We need to have one single place where the version is declared and that's what gets updated and used by the Designer and Turbo codegen. It would be best if this could be in the `pom.xml` and somehow injected into the the source or properties files of XOOM Designer and Turbo in that one single place.

/cc @danilo-ambrosio @jakzal

**Comment by hurelhuyag** [comment]
@VaughnVernon I updated. Now, this is working.

**Review by VaughnVernon — APPROVED** [review]
@hurelhuyag  Excellent, thanks! 🥇

**Review by jakzal — APPROVED** [review]

**Comment by danilo-ambrosio** [comment]
Back in the early versions of `vlingo-xoom`, the ${vlingo.xoom.version} was introduced for the purpose of preventing hard code versions. Thanks for making it right @hurelhuyag.

**Pull request merged**
