### PR TITLE
XOOM Designer: Generate GET {id}

### PR DESCRIPTION
**Pull request by hurelhuyag**
https://trello.com/c/cxKhtN3a/144-xoom-designer-generate-get-id-161

### CODE REVIEW

**Comment by hurelhuyag** [comment]
After many hours of investigation still can't figure out how to fix this.
Screenshot from 2021-04-05 13-17-58

**Comment by VaughnVernon** [comment]
@hurelhuyag How to fix what, specifically?

Is the code working that you have committed?

**Comment by VaughnVernon** [comment]
@hurelhuyag Thanks. Based on @danilo-ambrosio review and tweaks, is this ready to merge?

**Comment by hurelhuyag** [comment]
@VaughnVernon Yes, We can merge now.

**Comment by hurelhuyag** [comment]
@VaughnVernon I noticed another issue. Location header of Not found response is incorrectly generated.

```java
  public Completes<Response> aggOf(final String id) {
    return $queries.aggOf(id)
            .andThenTo(data -> Completes.withSuccess(Response.of(Ok, serialized(data))))
            .otherwise(arg -> Response.of(NotFound, location()))
            .recoverFrom(e -> Response.of(InternalServerError, e.getMessage()));
  }
```

**Comment by hurelhuyag** [comment]
> @VaughnVernon I noticed another issue. Location header of Not found response is incorrectly generated.
> 
> ```java
>   public Completes<Response> aggOf(final String id) {
>     return $queries.aggOf(id)
>             .andThenTo(data -> Completes.withSuccess(Response.of(Ok, serialized(data))))
>             .otherwise(arg -> Response.of(NotFound, location())) // <==== this should be location(id)
>             .recoverFrom(e -> Response.of(InternalServerError, e.getMessage()));
>   }
> ```

@danilo-ambrosio Please look into this. I think `location()` should be `location(id)`

**Comment by VaughnVernon** [comment]
@hurelhuyag This should be easy to fix. A `Not Found` should never have a `Location` header:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Location

**Comment by hurelhuyag** [comment]
@VaughnVernon  I just find out this is not a header. This is response body data. On the other hand, We never get Not Found response from this endpoint.

**Pull request merged**
