### PR TITLE
Add related documentation link in templates

### PR DESCRIPTION
**Pull request by hurelhuyag**

### CODE REVIEW

**Review by VaughnVernon — APPROVED** [review]
@hurelhuyag  Looks great, thanks! 👍

**Comment by VaughnVernon** [comment]
@hurelhuyag Nice work. How much more is there to do to be added to this PR?

**Comment by hurelhuyag** [comment]
@VaughnVernon This is all I found. I can't find some classes from documentation. For Example `IdentifiedDomainEvent`

**Comment by VaughnVernon** [comment]
@hurelhuyag Thanks for calling out the missing docs.

https://docs.vlingo.io/vlingo-lattice/entity-cqrs#commands-domain-events-and-identified-domain-events

Are there any others?

**Comment by hurelhuyag** [comment]
I think this 2 are last ones.
`StateObject` from `AggregateState.ftl`
`StateStoreQueryActor` from `QueriesActor.ftl`

**Comment by VaughnVernon** [comment]
> I think this 2 are last ones.
> `StateObject` from `AggregateState.ftl`
> `StateStoreQueryActor` from `QueriesActor.ftl`

@hurelhuyag Did you not find the docs for these?

**Comment by hurelhuyag** [comment]
> > I think this 2 are last ones.
> > `StateObject` from `AggregateState.ftl`
> > `StateStoreQueryActor` from `QueriesActor.ftl`
> 
> @hurelhuyag Did you not find the docs for these?

No. I did not find docs for these 2 classes.

**Comment by VaughnVernon** [comment]
@hurelhuyag Thanks. Here's `StateObject`:

See opening section:
https://docs.vlingo.io/vlingo-symbio/object-storage

And the second:
https://docs.vlingo.io/vlingo-lattice/entity-cqrs#querying-a-statestore

**Comment by hurelhuyag** [comment]
Second link is not working.

**Comment by VaughnVernon** [comment]
@hurelhuyag Oops. Try this one.

https://docs.vlingo.io/vlingo-lattice/entity-cqrs#querying-a-statestore

**Pull request merged**
