### PR TITLE
kotlin code templates

### PR DESCRIPTION
**Pull request by hurelhuyag**

### CODE REVIEW

**Comment by VaughnVernon** [comment]
@hurelhuyag Excellent. Can you also create a pom.xml. ftl for the Kotlin generation that has all the Kotlin compiler properties and library dependencies?

@danilo-ambrosio Please review. I'd like to add Kotlin support to codegen asap. I am not sure if that requires work beyond the ftl files. Of course we now need a radio button to select between Java and Kotlin. I'm sure there are some additions to the pom.xml for Kotlin complier. I have asked @hurelhuyag to help with that. We should probably also have a pom.xml.ftl for Java. (I haven't seen that).

NOTE: Kotlin support in XOOM Starter was one of the top wish list items from the RDDD Workshop survey.

**Comment by hurelhuyag** [comment]
@VaughnVernon Ok. Let's see what can I do.

**Comment by hurelhuyag** [comment]
Which main method do we use?
```java
class AnotherMain {

    init{
        println("Another Main");
    }

    companion object{
        @JvmStatic
        fun main(args: Array<String>){
            AnotherMain()
        }
    }
}

object Test{

    @JvmStatic
    fun main(args: Array<String>){
        AnotherMain()
    }
}

fun main(args: Array<String>){
    AnotherMain()
}
```

**Comment by VaughnVernon** [comment]
I think this one:

```
fun main(args: Array<String>) {
    Bootstrap()
}
```

**Comment by hurelhuyag** [comment]
I made my last changes that got in my mind. But still not sure if this bug free or not.

**Comment by VaughnVernon** [comment]
@danilo-ambrosio Please review and merge. I would like to have Kotlin implemented before VOs are completed.

**Review by danilo-ambrosio — APPROVED** [review]
Well done @hurelhuyag ! I will merge it into the `feature/polyglot` branch where I'm implementing the multi-language support on Starter.

**Pull request merged**
